use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use simthing_clausething::parse_stellaris_star_name_catalog;
use simthing_mapeditor::{
    canonicalize_tp_base_disc_scenario, generate_tp_base_disc_artifact,
    generate_tp_base_disc_artifact_from_recorded_metadata, tp_base_disc_generation_profile,
    tp_base_disc_star_name_corpus_source, StudioSession, TP_BASE_DISC_LATTICE_EDGE,
    TP_BASE_DISC_NAME_ASSIGNMENT_MODE, TP_BASE_DISC_NAME_CORPUS_SOURCE, TP_BASE_DISC_SCENARIO_ID,
    TP_BASE_DISC_SEED, TP_BASE_DISC_STARS,
};
use simthing_spec::{
    load_scenario_spec_from_json_str, save_scenario_spec_to_canonical_json,
    star_system_display_name,
};

const FIXTURE_RELATIVE_PATH: &str = "tests/fixtures/tp_base_disc_1500.simthing-scenario.json";

#[test]
fn tp_base_disc_regenerates_byte_identically_from_recorded_metadata() {
    let generated = generate_tp_base_disc_artifact().expect("generate canonical TP base disc");
    assert_eq!(generated.map_quality_status, "PASS");
    assert_eq!(generated.scenario.scenario_id, TP_BASE_DISC_SCENARIO_ID);
    assert_eq!(
        generated.scenario.provenance.generator_seed,
        TP_BASE_DISC_SEED
    );
    assert_eq!(generated.scenario.provenance.generator_shape, "elliptical");
    assert_eq!(
        generated.scenario.provenance.name_corpus_source,
        TP_BASE_DISC_NAME_CORPUS_SOURCE
    );
    assert_eq!(
        generated.scenario.provenance.name_assignment_mode,
        TP_BASE_DISC_NAME_ASSIGNMENT_MODE
    );
    assert!(generated
        .scenario
        .provenance
        .generator_params_json
        .contains("\"num_stars\": 1500"));

    let fixture = fixture_bytes();
    assert_eq!(
        generated.canonical_json, fixture,
        "canonical fixture must match generated bytes; set UPDATE_TP_BASE_DISC_FIXTURE=1 to refresh intentionally"
    );

    let (loaded, _report) =
        load_scenario_spec_from_json_str(FIXTURE_RELATIVE_PATH, &fixture).expect("load fixture");
    let regenerated = generate_tp_base_disc_artifact_from_recorded_metadata(&loaded.provenance)
        .expect("regenerate from recorded metadata");
    assert_eq!(regenerated.canonical_json, fixture);
    assert_eq!(regenerated.authority_digest, generated.authority_digest);
}

#[test]
fn tp_base_disc_studio_generate_path_matches_canonical_artifact() {
    let profile = tp_base_disc_generation_profile();
    let output = simthing_mapeditor::generation::run_generation(&profile).expect("studio generate");
    let temp = tempfile::tempdir().expect("tempdir");
    let corpus_path = temp.path().join("tp_base_disc_star_names.clause");
    fs::write(&corpus_path, tp_base_disc_star_name_corpus_source()).expect("write corpus");

    let mut studio_profile = profile.clone();
    studio_profile.star_name_corpus_path = corpus_path.display().to_string();
    let mut session =
        StudioSession::from_generation(studio_profile.clone(), output).expect("studio session");
    canonicalize_tp_base_disc_scenario(&mut session.scenario_authority, &studio_profile)
        .expect("canonicalize studio scenario");
    let studio_json = save_scenario_spec_to_canonical_json(&session.scenario_authority)
        .expect("studio canonical save")
        .canonical_json;

    let canonical = generate_tp_base_disc_artifact().expect("canonical artifact");
    assert_eq!(studio_json, canonical.canonical_json);
}

#[test]
fn tp_base_disc_names_are_seeded_and_map_quality_passes() {
    let artifact = generate_tp_base_disc_artifact().expect("artifact");
    let scenario = &artifact.scenario;
    assert_eq!(
        scenario.structural_grid.frame.width,
        TP_BASE_DISC_LATTICE_EDGE
    );
    assert_eq!(
        scenario.structural_grid.frame.occupied_cells,
        u64::from(TP_BASE_DISC_STARS)
    );
    assert_eq!(
        scenario.structural_grid.placements.len(),
        TP_BASE_DISC_STARS as usize
    );
    assert_eq!(artifact.map_quality_status, "PASS");

    let actual_names = assigned_display_names_by_system_id(scenario);
    let names: Vec<_> = actual_names.values().cloned().collect();
    assert_eq!(names.len(), TP_BASE_DISC_STARS as usize);
    assert_eq!(
        names.len(),
        names.iter().collect::<BTreeSet<_>>().len(),
        "canonical corpus has one unique authored name per generated star"
    );

    let catalog =
        parse_stellaris_star_name_catalog(tp_base_disc_star_name_corpus_source().as_bytes())
            .expect("catalog");
    let repeat = catalog.assign_to_systems(
        TP_BASE_DISC_SEED,
        scenario
            .structural_grid
            .placements
            .iter()
            .map(|placement| placement.system_id),
    );
    assert_eq!(actual_names, repeat);
}

fn fixture_bytes() -> String {
    let path = fixture_path();
    let generated = generate_tp_base_disc_artifact().expect("generate fixture candidate");
    if std::env::var_os("UPDATE_TP_BASE_DISC_FIXTURE").is_some() {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create fixture dir");
        }
        fs::write(&path, &generated.canonical_json).expect("write fixture");
    }
    fs::read_to_string(path).expect("read committed fixture")
}

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_RELATIVE_PATH)
}

fn assigned_display_names_by_system_id(
    scenario: &simthing_spec::SimThingScenarioSpec,
) -> BTreeMap<u32, String> {
    let map = scenario.galaxy_map_container().expect("map container");
    let mut out = BTreeMap::new();
    for placement in &scenario.structural_grid.placements {
        let cell = map
            .children
            .iter()
            .find(|child| child.id.raw() == placement.simthing_id_raw)
            .expect("gridcell");
        out.insert(
            placement.system_id,
            star_system_display_name(cell).expect("display name"),
        );
    }
    out
}
