//! Rich report formatting for overlay order-band semantics spike.

use crate::overlay_order::OverlayOrderReport;

pub fn format_overlay_order_report(report: &OverlayOrderReport) -> String {
    format!(
        "Overlay order-band semantics report\n\
         scenario: {}\n\
         n_slots: {}\n\
         n_cols: {}\n\
         n_values: {}\n\
         raw_overlay_count: {}\n\
         compiled_op_count: {}\n\
         compression_ratio: {:.4}\n\
         band_count: {}\n\
         max_ops_per_slot_col: {}\n\
         \n\
         Correctness:\n\
           max_abs_error: {}\n\
           mean_abs_error: {}\n\
           bit_exact: {}\n\
           within_loose_tolerance: {}\n\
           current_deterministic: {}\n\
           pivot_deterministic: {}\n\
         \n\
         Timing:\n\
           cpu_current_us: {}\n\
           cpu_compile_us: {}\n\
           current_warm_mean_us: {}\n\
           current_warm_min_us: {}\n\
           current_warm_max_us: {}\n\
           pivot_warm_mean_us: {}\n\
           pivot_warm_min_us: {}\n\
           pivot_warm_max_us: {}\n\
           speedup_pivot_vs_current: {:.3}x\n\
         \n\
         Interpretation:\n\
           semantic_gate: {}\n\
           determinism_gate: {}\n\
           performance_interpretation: {}\n\
           risk_interpretation: {}\n\
           note: {}\n\
         \n\
         Disclaimer: workshop-local; current path models overlay clutter stress; pivot path tests conservative order-band compilation; warm timings include upload/dispatch/readback.",
        report.scenario_name,
        report.n_slots,
        report.n_cols,
        report.n_values,
        report.raw_overlay_count,
        report.compiled_op_count,
        report.compression_ratio,
        report.band_count,
        report.max_ops_per_slot_col,
        report.max_abs_error,
        report.mean_abs_error,
        report.bit_exact,
        report.within_loose_tolerance,
        report.current_deterministic,
        report.pivot_deterministic,
        report.cpu_current_us,
        report.cpu_compile_us,
        report.current_warm_mean_us,
        report.current_warm_min_us,
        report.current_warm_max_us,
        report.pivot_warm_mean_us,
        report.pivot_warm_min_us,
        report.pivot_warm_max_us,
        report.speedup_pivot_vs_current,
        report.semantic_gate,
        report.determinism_gate,
        report.performance_interpretation,
        report.risk_interpretation,
        report.timing_note,
    )
}

pub fn write_overlay_order_reports(report: &OverlayOrderReport) -> std::io::Result<()> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/workshop");
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        dir.join("overlay_order_report.md"),
        format_overlay_order_report(report),
    )?;
    let json = serde_json::to_string_pretty(report).unwrap_or_else(|_| "{}".to_string());
    std::fs::write(dir.join("overlay_order_report.json"), json)?;
    Ok(())
}

pub fn write_overlay_order_semantics_reports_bundle(
    reports: &[OverlayOrderReport],
) -> std::io::Result<()> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/overlay_order_semantics_reports.txt");
    let mut body = String::from(
        "Overlay order-band semantics test reports (3 scenarios)\n\
         Generated by overlay_order_semantics_report_bundle\n\n",
    );
    for (idx, report) in reports.iter().enumerate() {
        body.push_str(&format!("========== SCENARIO {} ==========\n\n", idx + 1));
        body.push_str(&format_overlay_order_report(report));
        body.push_str("\n\n");
    }
    std::fs::write(path, body)
}
