//! Rich report formatting for persistent-buffer / timestamp benchmark spike.

use crate::persistent_bench::PersistentBenchReport;

pub fn format_persistent_bench_report(report: &PersistentBenchReport) -> String {
    format!(
        "Persistent-buffer / timestamp benchmark report\n\
         scenario: {}\n\
         n_pools: {}\n\
         n_queues: {}\n\
         ticks: {}\n\
         log_mode: {}\n\
         timestamp_supported: {}\n\
         timestamp_period_ns: {:.3}\n\
         \n\
         Correctness:\n\
           correctness_gate: {}\n\
           conservation_gate: {}\n\
           determinism_gate: {}\n\
           timestamp_gate: {}\n\
           performance_gate: {}\n\
           final_state_matches_cpu: {}\n\
           summaries_match_cpu: {}\n\
           repeated_pivot_outputs_identical: {}\n\
         \n\
         Route A — CPU boundary:\n\
           cpu_total_us: {}\n\
           cpu_per_tick_us: {:.3}\n\
         \n\
         Route B — current GPU envelope (per-tick upload/readback):\n\
           current_gpu_envelope_total_us: {}\n\
           current_gpu_envelope_per_tick_us: {:.3}\n\
           current_gpu_speedup_vs_cpu: {:.3}x\n\
         \n\
         Route C — pivot GPU resident persistent:\n\
           pivot_total_validation_mean_us: {}\n\
           pivot_total_validation_min_us: {}\n\
           pivot_total_validation_max_us: {}\n\
           pivot_total_validation_per_tick_us: {:.3}\n\
           pivot_validation_speedup_vs_cpu: {:.3}x\n\
           pivot_validation_speedup_vs_current_gpu: {:.3}x\n\
           pivot_timestamp_total_ns: {}\n\
           pivot_timestamp_per_tick_ns: {:.3}\n\
         \n\
         Data movement:\n\
           summary_bytes_total: {}\n\
           record_bytes_total: {}\n\
           final_state_bytes: {}\n\
         \n\
         Interpretation:\n\
           {}\n\
         note: {}\n\
         \n\
         Disclaimer: workshop-local; not production AccumulatorOp; one-invocation-per-pool; hotspot caveat separate from persistence benefit.",
        report.scenario_name,
        report.n_pools,
        report.n_queues,
        report.ticks,
        report.log_mode,
        report.timestamp_supported,
        report.timestamp_period_ns,
        report.correctness_gate,
        report.conservation_gate,
        report.determinism_gate,
        report.timestamp_gate,
        report.performance_gate,
        report.final_state_matches_cpu,
        report.summaries_match_cpu,
        report.repeated_pivot_outputs_identical,
        report.cpu_total_us,
        report.cpu_per_tick_us,
        report.current_gpu_envelope_total_us,
        report.current_gpu_envelope_per_tick_us,
        report.current_gpu_speedup_vs_cpu,
        report.pivot_total_validation_mean_us,
        report.pivot_total_validation_min_us,
        report.pivot_total_validation_max_us,
        report.pivot_total_validation_per_tick_us,
        report.pivot_validation_speedup_vs_cpu,
        report.pivot_validation_speedup_vs_current_gpu,
        report.pivot_timestamp_total_ns,
        report.pivot_timestamp_per_tick_ns,
        report.summary_bytes_total,
        report.record_bytes_total,
        report.final_state_bytes,
        report.interpretation,
        report.timing_note,
    )
}

pub fn write_persistent_bench_reports(report: &PersistentBenchReport) -> std::io::Result<()> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/workshop");
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        dir.join("persistent_bench_report.md"),
        format_persistent_bench_report(report),
    )?;
    let json = serde_json::to_string_pretty(report).unwrap_or_else(|_| "{}".to_string());
    std::fs::write(dir.join("persistent_bench_report.json"), json)?;
    Ok(())
}

pub fn write_persistent_bench_reports_bundle(
    reports: &[PersistentBenchReport],
) -> std::io::Result<()> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/persistent_bench_reports.txt");
    let mut body = String::from(
        "Persistent-buffer / timestamp benchmark reports (3 scenarios)\n\
         Generated by persistent_bench_report_bundle\n\n",
    );
    for (idx, report) in reports.iter().enumerate() {
        body.push_str(&format!("========== SCENARIO {} ==========\n\n", idx + 1));
        body.push_str(&format_persistent_bench_report(report));
        body.push_str("\n\n");
    }
    std::fs::write(path, body)
}
