//! Rich report formatting for transfer / emission contention spike.

use crate::transfer_contention::TransferContentionReport;

pub fn format_transfer_contention_report(report: &TransferContentionReport) -> String {
    format!(
        "Transfer / emission contention report\n\
         scenario: {}\n\
         n_pools: {}\n\
         n_queues: {}\n\
         n_requests: {}\n\
         ticks: {}\n\
         record_ticks: {}\n\
         records_memory_fallback: {}\n\
         queue_cross_pool_contention: {}\n\
         \n\
         Totals:\n\
           total_pool_before: {}\n\
           total_pool_after: {}\n\
           total_queue_accum_before: {}\n\
           total_queue_accum_after: {}\n\
           total_units_before: {}\n\
           total_units_after: {}\n\
           total_requested: {}\n\
           total_allocated: {}\n\
           total_emitted_value: {}\n\
         \n\
         Correctness:\n\
           final_state_matches_cpu_summary_mode: {}\n\
           final_state_matches_cpu_records_mode: {}\n\
           summaries_match_cpu: {}\n\
           replay_from_records_matches_gpu: {}\n\
           conservation_gate: {}\n\
           priority_gate: {}\n\
           replay_gate: {}\n\
           determinism_gate: {}\n\
           performance_gate: {}\n\
         \n\
         Timing:\n\
           cpu_n_ticks_us: {}\n\
           cpu_per_tick_us: {:.3}\n\
           gpu_summary_submit_mean_us: {}\n\
           gpu_summary_total_mean_us: {}\n\
           gpu_summary_total_per_tick_us: {:.3}\n\
           gpu_records_submit_mean_us: {}\n\
           gpu_records_total_mean_us: {}\n\
           gpu_records_total_per_tick_us: {:.3}\n\
           summary_speedup_vs_cpu: {:.3}x (total_validation)\n\
           records_speedup_vs_cpu: {:.3}x (total_validation)\n\
         \n\
         Data movement:\n\
           summary_bytes_total: {}\n\
           compact_record_bytes_total: {}\n\
         \n\
         Interpretation:\n\
           {}\n\
         note: {}\n\
         \n\
         Disclaimer: workshop-local; v1 pool-contention only; CPU-compiled request ordering; not production AccumulatorOp; no atomics; not pure shader timestamp timing.",
        report.scenario_name,
        report.n_pools,
        report.n_queues,
        report.n_requests,
        report.ticks,
        report.record_ticks,
        report.records_memory_fallback,
        report.queue_cross_pool_contention,
        report.total_pool_before,
        report.total_pool_after,
        report.total_queue_accum_before,
        report.total_queue_accum_after,
        report.total_units_before,
        report.total_units_after,
        report.total_requested,
        report.total_allocated,
        report.total_emitted_value,
        report.final_state_matches_cpu_summary_mode,
        report.final_state_matches_cpu_records_mode,
        report.summaries_match_cpu,
        report.replay_from_records_matches_gpu,
        report.conservation_gate,
        report.priority_gate,
        report.replay_gate,
        report.determinism_gate,
        report.performance_gate,
        report.cpu_n_ticks_us,
        report.cpu_per_tick_us,
        report.gpu_summary_submit_mean_us,
        report.gpu_summary_total_mean_us,
        report.gpu_summary_total_per_tick_us,
        report.gpu_records_submit_mean_us,
        report.gpu_records_total_mean_us,
        report.gpu_records_total_per_tick_us,
        report.summary_speedup_vs_cpu,
        report.records_speedup_vs_cpu,
        report.summary_bytes_total,
        report.compact_record_bytes_total,
        report.interpretation,
        report.timing_note,
    )
}

pub fn write_transfer_contention_reports(report: &TransferContentionReport) -> std::io::Result<()> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/workshop");
    std::fs::create_dir_all(&dir)?;
    std::fs::write(
        dir.join("transfer_contention_report.md"),
        format_transfer_contention_report(report),
    )?;
    let json = serde_json::to_string_pretty(report).unwrap_or_else(|_| "{}".to_string());
    std::fs::write(dir.join("transfer_contention_report.json"), json)?;
    Ok(())
}

pub fn write_transfer_contention_reports_bundle(
    reports: &[TransferContentionReport],
) -> std::io::Result<()> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/transfer_contention_reports.txt");
    let mut body = String::from(
        "Transfer / emission contention test reports (3 scenarios)\n\
         Generated by transfer_contention_report_bundle\n\n",
    );
    for (idx, report) in reports.iter().enumerate() {
        body.push_str(&format!("========== SCENARIO {} ==========\n\n", idx + 1));
        body.push_str(&format_transfer_contention_report(report));
        body.push_str("\n\n");
    }
    std::fs::write(path, body)
}
