// TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0R: CPU-only metadata table for all retired hygiene-theater inputs.

struct HygieneTheaterCase {
    source_crate: &'static str,
    original_file: &'static str,
    original_binary: &'static str,
    original_test: &'static str,
    classifier_input: &'static str,
    consolidation_wave: &'static str,
    expected_disposition: &'static str,
}

const CONSOLIDATION_TARGET: &str = "table::track-d::hygiene_theater_cases";
const CONSOLIDATION_WAVE: &str = "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0";

const HYGIENE_THEATER_CASES: &[HygieneTheaterCase] = &[
    HygieneTheaterCase {
        source_crate: "simthing-clausething",
        original_file: "crates/simthing-clausething/tests/ct_1b_recalc.rs",
        original_binary: "ct_1b_recalc",
        original_test: "ct_1b_recalc_stress_measurement",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/bh2d_ct4b_fixture.rs",
        original_binary: "bh2d_ct4b_fixture",
        original_test: "bh2d_overlap_stress_available_as_field_policy_feedstock",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/bh2d_ct4b_fixture.rs",
        original_binary: "bh2d_ct4b_fixture",
        original_test: "bh2d_stress_operators_are_overlap_and_mismatch_only",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e11_resource_flow_soak.rs",
        original_binary: "e11_resource_flow_soak",
        original_test: "e11_soak_flag_default_false",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e11_resource_flow_soak.rs",
        original_binary: "e11_resource_flow_soak",
        original_test: "e11_soak_flat_star_only_no_nested_claims",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e11_resource_flow_soak.rs",
        original_binary: "e11_resource_flow_soak",
        original_test: "e11_soak_repeated_resync_100_cycles_stable",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e11_resource_flow_soak.rs",
        original_binary: "e11_resource_flow_soak",
        original_test: "e11_soak_zero_weights_1000_ticks_no_nan",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_contiguity_blocked_no_compaction",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_flag_off_updates_registry_but_no_gpu_sync",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_multiple_fissions_100_ticks_stable",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_no_new_wgsl",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_no_simthing_sim_arena_imports",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_replay_same_seed_same_dynamic_enrollment_frames",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_resource_flow_flag_default_false",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/e2b5_dynamic_enrollment_soak.rs",
        original_binary: "e2b5_dynamic_enrollment_soak",
        original_test: "e2b5_soak_two_arenas_dynamic_enrollment_100_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/mobility_runtime1b_gpu_passgraph_fixture.rs",
        original_binary: "mobility_runtime1b_gpu_passgraph_fixture",
        original_test: "runtime1b_34k_gpu_fixture_soak_or_precise_blocker",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/palma_path_4_benchmark.rs",
        original_binary: "palma_path_4_benchmark",
        original_test: "palma_path_4_benchmark_full_matrix",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/palma_path_4_benchmark.rs",
        original_binary: "palma_path_4_benchmark",
        original_test: "palma_path_4_benchmark_smoke_matrix",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/palma_path_4_benchmark.rs",
        original_binary: "palma_path_4_benchmark",
        original_test: "palma_path_4_dijkstra_baseline_matches_min_plus_when_relaxed_enough",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/palma_path_4_benchmark.rs",
        original_binary: "palma_path_4_benchmark",
        original_test: "palma_path_4s_scenario_has_100_stars_and_150_fleets",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/palma_path_4_benchmark.rs",
        original_binary: "palma_path_4_benchmark",
        original_test: "palma_path_4s_stellaris_scale_benchmark",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_benchmark_report_smoke",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_generic_kernel_matches_existing_ao_for_a0_d3_nested_resource_flow",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_generic_kernel_matches_existing_ao_for_a0_d4_nested_resource_flow",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_generic_kernel_matches_existing_ao_for_b0_transfer_orderband_if_supported",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_generic_kernel_matches_existing_ao_for_flat_star",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_no_default_on_resource_flow_or_hard_currency_reroute",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_no_designer_authored_wgsl",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_no_l3_frontierv2_5_act_event_obs_pipe",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_no_simthing_sim_awareness",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_ao_wgsl0_accumulator_op_performance.rs",
        original_binary: "phase_ao_wgsl0_accumulator_op_performance",
        original_test: "ao_wgsl0_replay_reproducibility",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act0_numeric_proposals.rs",
        original_binary: "phase_m_field_policy_act0_numeric_proposals",
        original_test: "field_policy_act0_perf_34k_numeric_proposals",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act0_numeric_proposals.rs",
        original_binary: "phase_m_field_policy_act0_numeric_proposals",
        original_test: "field_policy_act0_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act1_phase_e_proposal_consumer.rs",
        original_binary: "phase_m_field_policy_act1_phase_e_proposal_consumer",
        original_test: "field_policy_act1_perf_34k_phase_e_consumer",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act1_phase_e_proposal_consumer.rs",
        original_binary: "phase_m_field_policy_act1_phase_e_proposal_consumer",
        original_test: "field_policy_act1_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act3_economic_fixture_records.rs",
        original_binary: "phase_m_field_policy_act3_economic_fixture_records",
        original_test: "field_policy_act3_perf_34k_fixture_records",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_act3_economic_fixture_records.rs",
        original_binary: "phase_m_field_policy_act3_economic_fixture_records",
        original_test: "field_policy_act3_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event0_compaction.rs",
        original_binary: "phase_m_field_policy_event0_compaction",
        original_test: "field_policy_event0_perf_34k_compaction",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event0_compaction.rs",
        original_binary: "phase_m_field_policy_event0_compaction",
        original_test: "field_policy_event0_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event1_code_bucketing.rs",
        original_binary: "phase_m_field_policy_event1_code_bucketing",
        original_test: "field_policy_event1_perf_34k_bucketing",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event1_code_bucketing.rs",
        original_binary: "phase_m_field_policy_event1_code_bucketing",
        original_test: "field_policy_event1_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event2_bucket_reductions.rs",
        original_binary: "phase_m_field_policy_event2_bucket_reductions",
        original_test: "field_policy_event2_perf_34k_bucket_reductions",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_event2_bucket_reductions.rs",
        original_binary: "phase_m_field_policy_event2_bucket_reductions",
        original_test: "field_policy_event2_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs0_mobile_overlay_score.rs",
        original_binary: "phase_m_field_policy_obs0_mobile_overlay_score",
        original_test: "field_policy_obs0_perf_34k_mobile_overlay_score",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs0_mobile_overlay_score.rs",
        original_binary: "phase_m_field_policy_obs0_mobile_overlay_score",
        original_test: "field_policy_obs1_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs2_multilayer_overlay_score.rs",
        original_binary: "phase_m_field_policy_obs2_multilayer_overlay_score",
        original_test: "field_policy_obs2_perf_34k_multilayer_overlay_score",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs2_multilayer_overlay_score.rs",
        original_binary: "phase_m_field_policy_obs2_multilayer_overlay_score",
        original_test: "field_policy_obs2_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs3_fixed_point_score.rs",
        original_binary: "phase_m_field_policy_obs3_fixed_point_score",
        original_test: "field_policy_obs3_perf_34k_fixed_score",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs3_fixed_point_score.rs",
        original_binary: "phase_m_field_policy_obs3_fixed_point_score",
        original_test: "field_policy_obs3_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs4_threshold_event.rs",
        original_binary: "phase_m_field_policy_obs4_threshold_event",
        original_test: "field_policy_obs4_perf_34k_threshold_event",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_obs4_threshold_event.rs",
        original_binary: "phase_m_field_policy_obs4_threshold_event",
        original_test: "field_policy_obs4_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_pipe0_observer_event_pipeline.rs",
        original_binary: "phase_m_field_policy_pipe0_observer_event_pipeline",
        original_test: "field_policy_pipe0_perf_34k_capacity_variants",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_pipe0_observer_event_pipeline.rs",
        original_binary: "phase_m_field_policy_pipe0_observer_event_pipeline",
        original_test: "field_policy_pipe0_perf_34k_integrated_pipeline",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_field_policy_pipe0_observer_event_pipeline.rs",
        original_binary: "phase_m_field_policy_pipe0_observer_event_pipeline",
        original_test: "field_policy_pipe0_perf_34k_warm_repeated_dispatch",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_exact_candidate_battery.rs",
        original_binary: "phase_m_jit_sqrt_exact_candidate_battery",
        original_test: "sqrt_exact4f_perf_e3_vs_f_smoke",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag0_f_exact_magnitude.rs",
        original_binary: "phase_m_jit_sqrt_mag0_f_exact_magnitude",
        original_test: "sqrt_mag0_perf_34k_mobile_simthing_hot_path",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag0_f_exact_magnitude.rs",
        original_binary: "phase_m_jit_sqrt_mag0_f_exact_magnitude",
        original_test: "sqrt_mag0_perf_scaled_smoke",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_0_fixed_exact.rs",
        original_binary: "phase_m_jit_sqrt_mag2_0_fixed_exact",
        original_test: "sqrt_mag2_0_perf_34k_fixed_mag2_plus_f_sqrt",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_candidate_a_q12_dense_corpus",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_candidate_c_split_kernels_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_correctness_edge_and_dense_q16",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_f_sqrt_only_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_fixed_mag2_only_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_fixed_mag2_plus_f_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_no_readback_dispatch_proxy_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_readback_baseline_34k",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/phase_m_jit_sqrt_mag2_perf0_fixed_hotpath.rs",
        original_binary: "phase_m_jit_sqrt_mag2_perf0_fixed_hotpath",
        original_test: "sqrt_mag2_perf0_scaled_smoke",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_does_not_enable_transfer_or_emission",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_dynamic_policy_a_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_flat_star_only_no_nested_claims",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_global_flag_default_false",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_multi_arena_no_coupling_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_no_new_wgsl",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_no_simthing_sim_arena_imports",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_populated_spec_without_opt_in_inactive",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_replay_same_seed_same_summary",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_static_512_participants_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_static_skewed_weights_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_flat_star_continued_soak.rs",
        original_binary: "resource_flow_flat_star_continued_soak",
        original_test: "rf_flat_star_continued_telemetry_has_flag_source_and_profile",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_disabled_populated_spec_inactive_but_reported",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_does_not_enable_transfer_or_emission",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_flat_star_only_no_nested_claims",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_global_resource_flow_flag_default_false",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_no_new_wgsl",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_no_simthing_sim_arena_imports",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_dynamic_fission_cadence_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_multi_arena_no_coupling_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_multi_session_replay_same_seed",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_repeated_resync_stable",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_static_128_participants_1000_ticks",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/resource_flow_opt_in_product_soak.rs",
        original_binary: "resource_flow_opt_in_product_soak",
        original_test: "rf_t3_product_static_256_participants_if_runtime_reasonable",
        classifier_input: "hygiene-theater soak classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-driver",
        original_file: "crates/simthing-driver/tests/session_integration.rs",
        original_binary: "session_integration",
        original_test: "bench_stress_scenarios_within_ceiling",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-gpu",
        original_file: "crates/simthing-gpu/tests/bh2s_overlap_stress.rs",
        original_binary: "bh2s_overlap_stress",
        original_test: "bh2s_binding_budget_caps_input_fields",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-gpu",
        original_file: "crates/simthing-gpu/tests/bh2s_overlap_stress.rs",
        original_binary: "bh2s_overlap_stress",
        original_test: "bh2s_no_native_sqrt_in_hot_path",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-gpu",
        original_file: "crates/simthing-gpu/tests/bh2s_overlap_stress.rs",
        original_binary: "bh2s_overlap_stress",
        original_test: "bh2s_velocity_stress_uses_prev_column_without_full_history",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_settings_renders_diagnostic_controls",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_settings_renders_frame_phase_section",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_does_not_mark_runtime_saveload_status_dirty",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_formats_build_profile",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_formats_frame_phase_ms",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_formats_gpu_adapter_unknown_gracefully",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_formats_present_mode_unknown_gracefully",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_frame_phase_gpu_telemetry.rs",
        original_binary: "studio_frame_phase_gpu_telemetry",
        original_test: "studio_performance_telemetry_formats_vram_as_tracked_assets_only",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_render_loop_dirty_gate.rs",
        original_binary: "studio_render_loop_dirty_gate",
        original_test: "performance_settings_render_loop_diagnostics_formats_counts",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_render_loop_dirty_gate.rs",
        original_binary: "studio_render_loop_dirty_gate",
        original_test: "performance_telemetry_remains_presentation_only",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_defaults_to_warming_up_without_diagnostics",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_does_not_mark_runtime_saveload_status_dirty",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_estimates_mesh_bytes",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_estimates_texture_bytes",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_formats_fps_with_one_decimal",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_performance_telemetry_formats_vram_in_mb",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_settings_window_includes_render_loop_diagnostics",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-mapeditor",
        original_file: "crates/simthing-mapeditor/tests/studio_settings_performance_telemetry.rs",
        original_binary: "studio_settings_performance_telemetry",
        original_test: "studio_settings_window_renders_performance_section",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-sim",
        original_file: "crates/simthing-sim/tests/c1_threshold_perf.rs",
        original_binary: "c1_threshold_perf",
        original_test: "c1_accumulator_threshold_readback_smoke",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-sim",
        original_file: "crates/simthing-sim/tests/c2_intent_perf.rs",
        original_binary: "c2_intent_perf",
        original_test: "c2_intent_perf_no_regression",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr5.rs",
        original_binary: "typeface_lr5",
        original_test: "ci_bench_budget_gates_pass",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr5.rs",
        original_binary: "typeface_lr5",
        original_test: "heavy_bench_manual",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "binding_perf_evidence_documented_for_lr9",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "flat_5k_binding_noop_perf_profile",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "flat_5k_noop_perf_profile_records_budget",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "numeric_damage_5k_binding_perf_profile",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "numeric_damage_5k_perf_profile_records_budget",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-tools",
        original_file: "crates/simthing-tools/tests/typeface_lr9.rs",
        original_binary: "typeface_lr9",
        original_test: "warped_nameplate_binding_perf_profile",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_distributed_100k_summary_only",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_distributed_1m",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_hotspot_100k_summary_only",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_records_mode_replays_small",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_report_bundle",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/persistent_bench.rs",
        original_binary: "persistent_bench",
        original_test: "persistent_bench_sparse_100k_summary_only",
        classifier_input: "hygiene-theater stress classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/weighted_mean_perf.rs",
        original_binary: "weighted_mean_perf",
        original_test: "weighted_mean_perf_dense_10k_x32_dims16_wm16",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/weighted_mean_perf.rs",
        original_binary: "weighted_mean_perf",
        original_test: "weighted_mean_perf_overlay_density_sweep",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
    HygieneTheaterCase {
        source_crate: "simthing-workshop",
        original_file: "crates/simthing-workshop/tests/weighted_mean_perf.rs",
        original_binary: "weighted_mean_perf",
        original_test: "weighted_mean_perf_sparse_100k_x32_dims64_wm1",
        classifier_input: "hygiene-theater perf/benchmark classifier input",
        consolidation_wave: "TEST-CONSOLIDATE-CLASSIFIER-FAMILIES-0",
        expected_disposition: "CONSOLIDATED_INPUT",
    },
];

#[test]
fn hygiene_theater_cases_table_preserves_inputs() {
    let mut seen = std::collections::BTreeSet::new();

    for case in HYGIENE_THEATER_CASES {
        assert!(!case.source_crate.is_empty(), "source_crate required for {}", case.original_test);
        assert!(!case.original_file.is_empty(), "original_file required for {}", case.original_test);
        assert!(!case.original_binary.is_empty(), "original_binary required for {}", case.original_test);
        assert!(!case.classifier_input.is_empty(), "classifier_input required for {}", case.original_test);
        assert_eq!(case.consolidation_wave, CONSOLIDATION_WAVE,
            "wave mismatch for {}::{}", case.original_binary, case.original_test);
        assert_eq!(case.expected_disposition, "CONSOLIDATED_INPUT",
            "disposition mismatch for {}::{}", case.original_binary, case.original_test);
        assert!(
            seen.insert((case.source_crate, case.original_file, case.original_test)),
            "duplicate classifier input case: {} {}::{}",
            case.source_crate, case.original_binary, case.original_test
        );
    }

    assert_eq!(HYGIENE_THEATER_CASES.len(), 132,
        "table row count must match consolidated classifier-input inventory");
    assert_eq!(CONSOLIDATION_TARGET, "table::track-d::hygiene_theater_cases");
}
